'use client';
import { useEffect, useState, type SyntheticEvent } from 'react';
import { Copy } from 'lucide-react';
import { call, useBuzz, refresh } from '@/lib/buzz/store';
import { isAdmin, type TeamSnapshot } from '@/lib/team-types';
export const teamAction = (values:Record<string,unknown>) => call<{token?:string;id?:string;expiresAt?:string;signInRequired?:boolean}>('/api/team',{method:'POST',body:JSON.stringify(values)});
export function TeamSettings() {
  const {members:agents}=useBuzz();
  const [team,setTeam]=useState<TeamSnapshot|null>(null),[message,setMessage]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[clock,setClock]=useState(()=>Date.now());
  const [inviteLink,setInviteLink]=useState<{id:string;url:string}|null>(null),[deviceSecret,setDeviceSecret]=useState('');
  const [cloud,setCloud]=useState<boolean|null>(null),[publicServers,setPublicServers]=useState<boolean|null>(null);
  const load=()=>call<TeamSnapshot>('/api/team',{}).then(data=>{setTeam(data);setCloud(value=>value??data.config.networkMode!=='lan');setPublicServers(value=>value??data.config.networkMode==='custom');});
  useEffect(()=>{void load().catch(error=>setError(error.message));const timer=setInterval(()=>{setClock(Date.now());void load().catch(error=>setError(error.message));},10000);return()=>clearInterval(timer);},[]);
  useEffect(()=>{if(!message)return;const timer=setTimeout(()=>setMessage(''),5000);return()=>clearTimeout(timer);},[message]);
  async function act(values:Record<string,unknown>,notice='Saved.') {
    if(busy)return;setBusy(true);setMessage('');setError('');
    try{const data=await teamAction(values);await load();await refresh();setMessage(notice);if(data.signInRequired)window.location.assign('/login');return data;}
    catch(error){setError(error instanceof Error?error.message:'Could not save.');}finally{setBusy(false);}
  }
  const form=(action:string,extra?:(values:Record<string,FormDataEntryValue>)=>Record<string,unknown>)=>(event:SyntheticEvent<HTMLFormElement,SubmitEvent>)=>{event.preventDefault();const values=Object.fromEntries(new FormData(event.currentTarget));void act({action,...values,...extra?.(values)});};
  async function copy(value:string){try{await navigator.clipboard.writeText(value);setMessage('Copied.');}catch{setError('Select the link and copy it manually.');}}
  if(!team)return <output>{error||'Loading settings'}</output>;
  const admin=isAdmin(team.user),config=team.config;
  const origin=config.publicUrl||(team.network.httpsEnabled&&team.network.addresses[0]?`https://${team.network.addresses[0]}:${team.network.httpsPort}`:window.location.origin);
  const localLink=['localhost','127.0.0.1','[::1]'].includes(new URL(origin).hostname);
  const invites=team.invites.filter(invite=>!invite.used_at&&!invite.revoked_at&&Date.parse(invite.expires_at)>clock);
  async function revoke(id:string){const result=await act({action:'revokeInvite',id},'Invitation revoked.');if(result&&inviteLink?.id===id)setInviteLink(null);}
  return <div className="team-form settings-content">
    {error&&<p className="settings-feedback team-error" role="alert">{error}</p>}{message&&<output className="settings-feedback" aria-live="polite">{message}</output>}
    {admin&&<section className="settings-section"><h2>Workspace</h2><form className="settings-name-form" onSubmit={form('config')}><label>Workspace name<input className="input" aria-label="Workspace name" name="name" defaultValue={config.name} required maxLength={60}/></label><button className="btn btn-primary" disabled={busy}>Save name</button></form></section>}
    <section className="settings-section"><header className="settings-section-heading"><h2>Team</h2></header>
      <div className="settings-list settings-team-list">{team.members.map(member=><div className="settings-member-row" key={member.id}><div><strong>{member.name}</strong><small>@{member.username}{!member.active?' / Disabled':''}</small></div>{admin&&member.role!=='owner'&&(team.user.role==='owner'||member.role!=='admin')?<div className="settings-row-actions"><select className="select" aria-label={'Role for '+member.name} value={member.role} disabled={busy} onChange={event=>void act({action:'member',id:member.id,role:event.target.value})}><option value="member">Member</option><option value="viewer">Viewer</option>{team.user.role==='owner'&&<option value="admin">Admin</option>}</select><button className="btn btn-secondary" disabled={busy} onClick={()=>void act({action:'member',id:member.id,active:!member.active})}>{member.active?'Disable':'Enable'}</button><button className="btn settings-danger" disabled={busy} onClick={()=>{if(window.confirm(`Remove ${member.name} from the workspace? Their access will end. Existing messages and files will stay.`))void act({action:'removeMember',id:member.id},'Member removed.');}}>Remove</button></div>:<span className="settings-role">{member.role}</span>}</div>)}</div>
      {admin&&<section className="invite-teammates" aria-label="Invite teammates"><h3>Invite teammates</h3>
        <form className="invite-form" onSubmit={async event=>{event.preventDefault();const values=Object.fromEntries(new FormData(event.currentTarget));const result=await act({action:'invite',...values},'Invitation created.');if(result?.token&&result.id)setInviteLink({id:result.id,url:origin+'/join#'+result.token});}}>
          <div className="invite-options"><label>Role<select className="select" name="role" aria-label="Invitation role" disabled={busy}><option value="member">Member</option><option value="viewer">Viewer</option>{team.user.role==='owner'&&<option value="admin">Admin</option>}</select></label><label>Expires in<select className="select" name="hours" aria-label="Invitation expiry" disabled={busy}><option value="24">24 hours</option><option value="1">1 hour</option><option value="168">7 days</option></select></label><button className="btn btn-primary" disabled={busy}>{busy?'Creating':'Create link'}</button></div>
          {inviteLink&&invites.some(invite=>invite.id===inviteLink.id)&&<div className="invite-result"><label htmlFor="invitation-link">Invitation link</label><div className="invite-link-row"><input id="invitation-link" className="input" readOnly value={inviteLink.url} onFocus={event=>event.target.select()}/><button type="button" className="btn btn-secondary" onClick={()=>void copy(inviteLink.url)}><Copy size={16}/>Copy</button><button type="button" className="btn settings-danger" disabled={busy} onClick={()=>void revoke(inviteLink.id)}>Revoke</button></div>{localLink&&<small className="team-error">Set a team address under Network to use this link on other computers.</small>}</div>}
        </form>
        {!!invites.filter(invite=>invite.id!==inviteLink?.id).length&&<div className="settings-invitations"><h3>Pending invitations</h3><div className="settings-list">{invites.filter(invite=>invite.id!==inviteLink?.id).map(invite=><div className="settings-invite-row" key={invite.id}><div><strong>{invite.role[0].toUpperCase()+invite.role.slice(1)}</strong><small>Expires {new Date(invite.expires_at).toLocaleString([], {month:'short',day:'numeric',hour:'numeric',minute:'2-digit'})}</small></div><button className="btn settings-danger" disabled={busy} onClick={()=>void revoke(invite.id)}>Revoke</button></div>)}</div></div>}
      </section>}
    </section>
    {admin&&<details className="settings-section settings-advanced"><summary>Advanced workspace settings</summary><div className="team-form">
      <details><summary>Network</summary><form className="team-form" onSubmit={form('config',()=>({networkMode:!cloud?'lan':publicServers?'custom':'connected'}))}>
        <label className="team-check"><input type="checkbox" aria-label="Allow cloud services" checked={!!cloud} disabled={busy} onChange={event=>{setCloud(event.target.checked);if(!event.target.checked)setPublicServers(false);}}/>Allow cloud AI and Google Drive</label>
        <label className="team-check"><input type="checkbox" aria-label="Allow public servers" checked={!!publicServers} disabled={busy||!cloud} onChange={event=>setPublicServers(event.target.checked)}/>Allow public model and database servers</label>
        <small>Local network services stay available. File classifications still apply.</small>
        <label>Team address<input className="input" type="url" name="publicUrl" aria-label="Team address" defaultValue={config.publicUrl} placeholder={origin}/><small>Used in invitation links.</small></label>
        <div className="settings-form-actions"><button className="btn btn-primary" disabled={busy}>Save network settings</button></div>
      </form>{team.network.httpsEnabled?<div className="settings-network"><span>LAN HTTPS is running</span>{team.network.addresses.map(address=><a key={address} href={`https://${address}:${team.network.httpsPort}`} target="_blank" rel="noreferrer">https://{address}:{team.network.httpsPort}</a>)}<a className="btn btn-secondary" href="/api/lan/certificate" download>Download device certificate</a></div>:<p>LAN HTTPS is off. Start the host with <code>npm run lan</code> to enable it.</p>}</details>
      <details><summary>Terminal</summary><form className="team-form" onSubmit={form('config',values=>({terminalEnabled:values.terminalEnabled==='on',terminalTimeout:Number(values.terminalTimeout)}))}><label className="team-check"><input name="terminalEnabled" type="checkbox" defaultChecked={config.terminalEnabled}/>Allow terminal commands</label><label>Member commands<select className="select" name="memberTerminal" defaultValue={config.memberTerminal}><option value="ask">Require admin approval</option><option value="off">Disabled</option></select></label><label>Working directory<input className="input" name="workDirectory" defaultValue={config.workDirectory} required/></label><label>Command timeout (seconds)<input className="input" type="number" name="terminalTimeout" defaultValue={config.terminalTimeout} min={5} max={1800} required/></label><div className="settings-form-actions"><button className="btn btn-primary" disabled={busy}>Save terminal settings</button></div></form></details>
      <details><summary>Who can use agents</summary><div className="settings-list">{agents.filter(agent=>agent.kind==='agent').map(agent=>{const selected=Array.isArray(agent.data.allowedUsers)?agent.data.allowedUsers as string[]:['*'];return <details key={agent.id}><summary>{agent.name} / {selected.includes('*')?'Everyone':selected.length+' people'}</summary>{[{id:'*',name:'Everyone'},...team.members.filter(member=>member.active)].map(member=><label className="team-check" key={member.id}><input type="checkbox" disabled={busy||(member.id!=='*'&&selected.includes('*'))} checked={selected.includes(member.id)} onChange={event=>void act({action:'agentAccess',id:agent.id,users:event.target.checked?member.id==='*'?['*']:[...selected,member.id]:selected.filter(id=>id!==member.id)})}/>{member.name}</label>)}</details>;})}{!agents.some(agent=>agent.kind==='agent')&&<p>No agents yet.</p>}</div></details>
      <details><summary>Command devices</summary><div className="team-form"><div className="settings-list">{team.devices.map(device=><div className="settings-member-row" key={device.id}><div><strong>{device.name}</strong><small>{!device.enabled?'Revoked':device.seen_at&&clock-Date.parse(device.seen_at)<15000?'Connected':'Offline'}</small><small>{device.work_directory}</small></div>{device.id!=='local'&&!!device.enabled&&<button className="btn settings-danger" disabled={busy} onClick={()=>void act({action:'revokeDevice',id:device.id})}>Revoke</button>}</div>)}</div>
        <form className="team-form" onSubmit={async event=>{event.preventDefault();const values=Object.fromEntries(new FormData(event.currentTarget));const result=await act({action:'device',...values},'Device registered.');if(result?.token)setDeviceSecret(`BUZZ_API=${origin}\nSHOAL_DEVICE_TOKEN=${result.token}\n${team.network.httpsEnabled?'NODE_EXTRA_CA_CERTS=./shoal-ca.crt\n':''}`);}}><label>Device name<input className="input" name="name" required maxLength={80} placeholder="Lab workstation"/></label><label>Working directory on the device<input className="input" name="workDirectory" required placeholder="/home/team/work"/></label><div className="settings-form-actions"><button className="btn btn-secondary" disabled={busy}>Register device</button></div></form>
        {deviceSecret&&<div className="team-form"><label>Save as .env.device<textarea className="team-secret" readOnly value={deviceSecret} onFocus={event=>event.target.select()}/></label><small>{team.network.httpsEnabled?'Copy the workspace certificate to shoal-ca.crt. ':''}Then run <code>npm run device</code> on that device.</small><div className="settings-row-actions"><button className="btn btn-secondary" onClick={()=>void copy(deviceSecret)}>Copy credentials</button><button className="btn btn-secondary" onClick={()=>setDeviceSecret('')}>Hide credentials</button></div></div>}
      </div></details>

    </div></details>}
    <details className="settings-section"><summary>Account</summary><div className="team-form"><div className="settings-member-row"><div><strong>{team.user.name}</strong><small>@{team.user.username}</small></div><button className="btn btn-secondary" onClick={async()=>{try{await call('/api/auth',{method:'DELETE'});window.location.assign('/login');}catch(error){setError(error instanceof Error?error.message:'Could not sign out.');}}}>Sign out</button></div>
      <form className="settings-name-form" onSubmit={form('profile')}><label>Display name<input className="input" name="name" defaultValue={team.user.name} required maxLength={60}/></label><button className="btn btn-secondary" disabled={busy}>Save display name</button></form>
      <details><summary>Change password</summary><form className="team-form" onSubmit={form('password')}><label>Current password<input className="input" name="oldPassword" type="password" autoComplete="current-password" required/></label><label>New password<input className="input" name="password" type="password" autoComplete="new-password" required minLength={12} maxLength={256}/></label><small>Changing your password signs out all devices.</small><div className="settings-form-actions"><button className="btn btn-secondary" disabled={busy}>Change password</button></div></form></details>
      <details><summary>Signed-in devices ({team.sessions.length})</summary><div className="settings-list">{team.sessions.map(session=><div className="settings-member-row" key={session.id}><div><strong>{session.current?'This browser':'Browser session'}</strong><small className="session-device">{session.device}</small></div><button className="btn btn-secondary" disabled={busy} onClick={()=>void act({action:'revokeSession',id:session.id},'Signed out.').then(result=>{if(result&&session.current)window.location.assign('/login');})}>Sign out</button></div>)}</div></details>
    </div></details>
  </div>;
}
