CREATE TABLE IF NOT EXISTS users(id TEXT PRIMARY KEY, username TEXT NOT NULL UNIQUE, password_hash TEXT NOT NULL, role TEXT NOT NULL, active INTEGER NOT NULL DEFAULT 1, created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS sessions(token_hash TEXT PRIMARY KEY, user_id TEXT NOT NULL REFERENCES users(id), device TEXT NOT NULL, created_at TEXT NOT NULL, expires_at TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS sessions_user ON sessions(user_id);
CREATE TABLE IF NOT EXISTS invites(id TEXT PRIMARY KEY, token_hash TEXT NOT NULL UNIQUE, role TEXT NOT NULL, created_by TEXT NOT NULL, created_at TEXT NOT NULL, expires_at TEXT NOT NULL, used_at TEXT, revoked_at TEXT);
CREATE TABLE IF NOT EXISTS team_activity(id INTEGER PRIMARY KEY AUTOINCREMENT, actor_id TEXT NOT NULL, action TEXT NOT NULL, detail TEXT NOT NULL, created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS execution_devices(id TEXT PRIMARY KEY, name TEXT NOT NULL, token_hash TEXT UNIQUE, work_directory TEXT NOT NULL, enabled INTEGER NOT NULL DEFAULT 1, seen_at TEXT, created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS terminal_jobs(id TEXT PRIMARY KEY, actor_id TEXT NOT NULL, device_id TEXT NOT NULL, command TEXT NOT NULL, cwd TEXT NOT NULL, status TEXT NOT NULL, output TEXT NOT NULL DEFAULT '', exit_code INTEGER, error TEXT, approved_by TEXT, created_at TEXT NOT NULL, started_at TEXT, ended_at TEXT, lease_until TEXT, runner_id TEXT, last_seq INTEGER NOT NULL DEFAULT 0, request_id TEXT NOT NULL UNIQUE);
CREATE INDEX IF NOT EXISTS terminal_queue ON terminal_jobs(status,created_at);
ALTER TABLE documents ADD COLUMN readers TEXT NOT NULL DEFAULT '[]';
ALTER TABLE runs ADD COLUMN requested_by TEXT;
UPDATE messages SET room='dm:you:' || substr(room,4) WHERE room LIKE 'dm:%' AND room NOT LIKE 'dm:%:%';
UPDATE runs SET room='dm:you:' || substr(room,4) WHERE room LIKE 'dm:%' AND room NOT LIKE 'dm:%:%';
UPDATE runs SET requested_by='you' WHERE requested_by IS NULL;
